"use client";

import { useState } from "react";
import { Loader2, Play, Check, X, GitPullRequest, Code2, AlertCircle } from "lucide-react";
import * as Diff from "diff";
import * as Diff2Html from "diff2html";
import "diff2html/bundles/css/diff2html.min.css";

interface Issue {
  number: number;
  title: string;
  body: string;
  html_url: string;
}

export interface RepoContext {
  owner: string;
  repo: string;
  defaultBranch: string;
  description: string;
  files: string[];
  issues: Issue[];
}

export function Workspace({ repoContext, onReset }: { repoContext: RepoContext; onReset: () => void }) {
  const [prompt, setPrompt] = useState("");
  const [isAgentRunning, setIsAgentRunning] = useState(false);
  const [agentStep, setAgentStep] = useState("");
  const [modifications, setModifications] = useState<{ path: string; originalContent: string; content: string }[] | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [prUrl, setPrUrl] = useState<string | null>(null);
  const [error, setError] = useState("");

  const handleRunAgent = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt) return;
    setIsAgentRunning(true);
    setModifications(null);
    setError("");
    setAgentStep("Initializing agent...");

    try {
      setAgentStep("Analyzing codebase & drafting changes...");
      const res = await fetch("/api/agent", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          owner: repoContext.owner,
          repo: repoContext.repo,
          defaultBranch: repoContext.defaultBranch,
          files: repoContext.files,
          prompt,
        }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Agent failed");

      setModifications(data.modifications);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsAgentRunning(false);
      setAgentStep("");
    }
  };

  const handleSubmitPR = async () => {
    if (!modifications) return;
    setIsSubmitting(true);
    setError("");

    try {
      const res = await fetch("/api/github/pr", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          owner: repoContext.owner,
          repo: repoContext.repo,
          defaultBranch: repoContext.defaultBranch,
          modifications,
          title: prompt.split('\n')[0].slice(0, 50),
          description: `This PR was automatically generated by PR-Creator AI.\n\n### Task\n${prompt}`,
        }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to submit PR");

      setPrUrl(data.url);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  const renderDiff = (mod: { path: string; originalContent: string; content: string }) => {
    const patch = Diff.createTwoFilesPatch(
      mod.path,
      mod.path,
      mod.originalContent || "",
      mod.content || "",
      "Original",
      "Modified"
    );

    const html = Diff2Html.html(patch, {
      drawFileList: false,
      matching: "lines",
      outputFormat: "line-by-line",
      colorScheme: "dark",
    });

    return <div dangerouslySetInnerHTML={{ __html: html }} className="diff-wrapper" />;
  };

  return (
    <div className="w-full max-w-7xl mx-auto flex flex-col lg:flex-row gap-6 animate-fade-in p-6 z-10">
      {/* Sidebar - Issues & Context */}
      <div className="w-full lg:w-1/3 flex flex-col gap-6">
        <div className="glass-panel p-6 flex flex-col">
          <div className="flex justify-between items-start mb-4">
            <div>
              <h2 className="text-xl font-bold flex items-center gap-2">
                <Code2 className="w-5 h-5 text-primary" />
                {repoContext.owner}/{repoContext.repo}
              </h2>
              <p className="text-sm text-muted mt-1">{repoContext.description || "No description"}</p>
            </div>
            <button onClick={onReset} className="text-muted hover:text-foreground">
              <X className="w-5 h-5" />
            </button>
          </div>
          <div className="flex gap-2 mb-4">
            <span className="bg-surface border border-surface-border px-2 py-1 rounded text-xs font-mono">
              Branch: {repoContext.defaultBranch}
            </span>
            <span className="bg-surface border border-surface-border px-2 py-1 rounded text-xs font-mono">
              {repoContext.files.length} files
            </span>
          </div>
        </div>

        <div className="glass-panel p-6 flex-1 max-h-[500px] overflow-y-auto">
          <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
            <AlertCircle className="w-5 h-5 text-accent" />
            Open Issues ({repoContext.issues.length})
          </h3>
          {repoContext.issues.length === 0 ? (
            <p className="text-muted text-sm">No open issues found.</p>
          ) : (
            <div className="flex flex-col gap-3">
              {repoContext.issues.map((issue) => (
                <div 
                  key={issue.number} 
                  className="p-3 bg-surface border border-surface-border rounded-lg hover:border-primary/50 cursor-pointer transition-colors"
                  onClick={() => setPrompt(`Fix Issue #${issue.number}: ${issue.title}\n\n${issue.body || ""}`)}
                >
                  <div className="font-medium text-sm text-primary mb-1">#{issue.number}</div>
                  <div className="text-sm line-clamp-2">{issue.title}</div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Main Area - Prompt & Diffs */}
      <div className="w-full lg:w-2/3 flex flex-col gap-6">
        <div className="glass-panel p-6">
          <form onSubmit={handleRunAgent} className="flex flex-col gap-4">
            <label className="text-lg font-bold">What would you like to build or fix?</label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g., Fix the navigation bar responsiveness, or implement the login page styling."
              className="input-base min-h-[120px] resize-y"
              required
            />
            <button 
              type="submit" 
              disabled={isAgentRunning || !prompt}
              className="btn-primary self-end"
            >
              {isAgentRunning ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  {agentStep}
                </>
              ) : (
                <>
                  <Play className="w-5 h-5" />
                  Run AI Engineer
                </>
              )}
            </button>
            {error && <div className="text-error text-sm mt-2">{error}</div>}
          </form>
        </div>

        {prUrl && (
           <div className="glass-panel p-6 border-success bg-success/10 flex flex-col items-center justify-center text-center animate-fade-in">
             <div className="w-16 h-16 bg-success rounded-full flex items-center justify-center mb-4">
               <Check className="w-8 h-8 text-black" />
             </div>
             <h3 className="text-2xl font-bold mb-2 text-success">Pull Request Submitted!</h3>
             <a href={prUrl} target="_blank" rel="noreferrer" className="text-primary hover:underline font-mono">
               {prUrl}
             </a>
           </div>
        )}

        {modifications && !prUrl && (
          <div className="glass-panel p-6 animate-fade-in flex flex-col gap-6">
            <div className="flex justify-between items-center bg-surface p-4 rounded-lg border border-surface-border">
              <div>
                <h3 className="text-xl font-bold">Ready to Merge</h3>
                <p className="text-muted text-sm">{modifications.length} files modified</p>
              </div>
              <button 
                onClick={handleSubmitPR} 
                disabled={isSubmitting}
                className="btn-primary !bg-success hover:!bg-success/80 text-black"
              >
                {isSubmitting ? (
                  <Loader2 className="w-5 h-5 animate-spin" />
                ) : (
                  <>
                    <GitPullRequest className="w-5 h-5" />
                    Submit Pull Request
                  </>
                )}
              </button>
            </div>

            <div className="flex flex-col gap-6">
              {modifications.map((mod, idx) => (
                <div key={idx} className="border border-surface-border rounded-lg overflow-hidden bg-background">
                  <div className="bg-surface px-4 py-2 border-b border-surface-border font-mono text-sm text-muted">
                    {mod.path}
                  </div>
                  <div className="p-4 overflow-x-auto text-sm">
                    {renderDiff(mod)}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
