import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "../../auth/[...nextauth]/route";
import { Octokit } from "octokit";

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || !session.accessToken) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { owner, repo, defaultBranch, modifications, title, description } = await req.json();

    if (!modifications || modifications.length === 0) {
      return NextResponse.json({ error: "No modifications provided" }, { status: 400 });
    }

    const octokit = new Octokit({ auth: session.accessToken });

    // 1. Get latest commit SHA of default branch
    const { data: refData } = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    const latestCommitSha = refData.object.sha;

    // 2. Create a new branch
    const newBranchName = `pr-creator-${Date.now()}`;
    await octokit.rest.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${newBranchName}`,
      sha: latestCommitSha,
    });

    // 3. Create blobs for each modified file
    const treeItems = [];
    for (const mod of modifications) {
      const { data: blobData } = await octokit.rest.git.createBlob({
        owner,
        repo,
        content: Buffer.from(mod.content, "utf-8").toString("base64"),
        encoding: "base64",
      });

      treeItems.push({
        path: mod.path,
        mode: "100644" as const,
        type: "blob" as const,
        sha: blobData.sha,
      });
    }

    // 4. Create a new tree
    const { data: treeData } = await octokit.rest.git.createTree({
      owner,
      repo,
      base_tree: latestCommitSha,
      tree: treeItems,
    });

    // 5. Create a commit
    const { data: commitData } = await octokit.rest.git.createCommit({
      owner,
      repo,
      message: `PR-Creator: ${title}`,
      tree: treeData.sha,
      parents: [latestCommitSha],
    });

    // 6. Update the branch ref
    await octokit.rest.git.updateRef({
      owner,
      repo,
      ref: `heads/${newBranchName}`,
      sha: commitData.sha,
    });

    // 7. Create Pull Request
    const { data: prData } = await octokit.rest.pulls.create({
      owner,
      repo,
      title: title || "Automated PR from PR-Creator",
      head: newBranchName,
      base: defaultBranch,
      body: description || "This pull request was automatically generated by PR-Creator AI.",
    });

    return NextResponse.json({ url: prData.html_url });
  } catch (error: any) {
    console.error("PR submission error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
